#!/usr/bin/env php
<?php
require __DIR__.'/../../vendor/autoload.php';

use Afosto\ApiClient\Generator\Generator;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Generator());
$application->run();